### ISSUE TITLE
文章链接有误

### ISSUE THREAD

**Issue by chenjuntong** [mywei1989/blog#2]
在[《React版博客系列4--Article组件与ArticleList组件》](http://nullcn.com/tag/react/)提供的系列链接中，

> 2.React版博客系列2--分页组件设计

> 3.React版博客系列3--路由系统

链接地址皆打不开，可能是月份写错，把url中的2改成3即可正常打开

**Comment by mywei1989** [comment]
感谢指出
目前文章全部迁移至hexo架构的博客了
旧版入口为 https://node.nullcn.com 
已经修复了链接
